# Data Transformation
LSE_ID = 250094127

## Loading the json files

First, I **import** the relevant libraries and load the raw movie details.

In [84]:
import pandas as pd 
import json
import sqlite3

In [85]:
with open("../data/raw/movie_details.json") as f:
    raw_details = json.load(f)

In [86]:
raw_details

{'movies': [{'adult': False,
   'backdrop_path': '/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg',
   'belongs_to_collection': {'id': 10,
    'name': 'Star Wars Collection',
    'poster_path': '/pWVLFh4OuejTpUaDQbB1C4zoS2p.jpg',
    'backdrop_path': '/iY2ujEY2m68OTTlPFTiHub9joHS.jpg'},
   'budget': 245000000,
   'genres': [{'id': 12, 'name': 'Adventure'},
    {'id': 28, 'name': 'Action'},
    {'id': 878, 'name': 'Science Fiction'}],
   'homepage': 'http://www.starwars.com/films/star-wars-episode-vii',
   'id': 140607,
   'imdb_id': 'tt2488496',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Star Wars: The Force Awakens',
   'overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
   'popularity': 21.4627,
   'poster_path': '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
   'production_companies': [{'id': 1,
     'logo_path': '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
     'name': 'Lucasfilm Ltd.',
     'origin_country': 'US'},
    {'id': 11461,
     'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
     'name': 'Bad Robot',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-12-15',
   'revenue': 2068223624,
   'runtime': 136,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'Every generation has a story.',
   'title': 'Star Wars: The Force Awakens',
   'video': False,
   'vote_average': 7.248,
   'vote_count': 20688},
  {'adult': False,
   'backdrop_path': '/dF6FjTZzRTENfB4R17HDN20jLT2.jpg',
   'belongs_to_collection': {'id': 328,
    'name': 'Jurassic Park Collection',
    'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
    'backdrop_path': '/njFixYzIxX8jsn6KMSEtAzi4avi.jpg'},
   'budget': 150000000,
   'genres': [{'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'},
    {'id': 53, 'name': 'Thriller'}],
   'homepage': 'https://www.jurassicworld.com/',
   'id': 135397,
   'imdb_id': 'tt0369610',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Jurassic World',
   'overview': 'Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.',
   'popularity': 18.7528,
   'poster_path': '/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg',
   'production_companies': [{'id': 56,
     'logo_path': '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
     'name': 'Amblin Entertainment',
     'origin_country': 'US'},
    {'id': 33,
     'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
     'name': 'Universal Pictures',
     'origin_country': 'US'},
    {'id': 923,
     'logo_path': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
     'name': 'Legendary Pictures',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-06-06',
   'revenue': 1671537444,
   'runtime': 124,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'The park is open.',
   'title': 'Jurassic World',
   'video': False,
   'vote_average': 6.703,
   'vote_count': 21726},
  {'adult': False,
   'backdrop_path': '/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg',
   'belongs_to_collection': {'id': 9485,
    'name': 'The Fast and the Furious Collection',
    'poster_path': '/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg',
    'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
   'budget': 190000000,
   'genres': [{'id': 28, 'name': 'Action'},
    {'id': 80, 'name': 'Crime'},
    {'id': 53, 'name': 'Thriller'}],
   'homepage': 'https://www.universalpicturesathome.com/movies/furious-7',
   'id': 168259,
   'imdb_id': 'tt2820852',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Furious 7',
   'overview': 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
   'popularity': 13.9605,
   'poster_path': '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
   'production_companies': [{'id': 333,
     'logo_path': '/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png',
     'name': 'Original Film',
     'origin_country': 'US'},
    {'id': 1225,
     'logo_path': '/rIxhJMR7oK8b2fMakmTfRLY2TZv.png',
     'name': 'One Race',
     'origin_country': 'US'},
    {'id': 33,
     'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
     'name': 'Universal Pictures',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-04-01',
   'revenue': 1515400000,
   'runtime': 138,
   'softcore': False,
   'spoken_languages': [{'english_name': 'Arabic',
     'iso_639_1': 'ar',
     'name': 'العربية'},
    {'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'},
    {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'},
    {'english_name': 'Thai', 'iso_639_1': 'th', 'name': 'ภาษาไทย'}],
   'status': 'Released',
   'tagline': 'Vengeance hits home.',
   'title': 'Furious 7',
   'video': False,
   'vote_average': 7.216,
   'vote_count': 11381},
  {'adult': False,
   'backdrop_path': '/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg',
   'belongs_to_collection': {'id': 86311,
    'name': 'The Avengers Collection',
    'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
    'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
   'budget': 235000000,
   'genres': [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'}],
   'homepage': 'https://www.marvel.com/movies/avengers-age-of-ultron',
   'id': 99861,
   'imdb_id': 'tt2395427',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Avengers: Age of Ultron',
   'overview': 'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
   'popularity': 33.7251,
   'poster_path': '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
   'production_companies': [{'id': 420,
     'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
     'name': 'Marvel Studios',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-04-22',
   'revenue': 1405403694,
   'runtime': 141,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'A new age has come.',
   'title': 'Avengers: Age of Ultron',
   'video': False,
   'vote_average': 7.275,
   'vote_count': 24664},
  {'adult': False,
   'backdrop_path': '/wKrxeY6lbu7KFBsWVcMH6M8avwr.jpg',
   'belongs_to_collection': {'id': 544669,
    'name': 'Minions Collection',
    'poster_path': '/lqU48HkuPDpbumwHk9syT7FbxpC.jpg',
    'backdrop_path': '/62Qe28oi9PaK3P2ljDYUDTGAyST.jpg'},
   'budget': 74000000,
   'genres': [{'id': 10751, 'name': 'Family'},
    {'id': 16, 'name': 'Animation'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 35, 'name': 'Comedy'}],
   'homepage': 'http://www.minionsmovie.com/',
   'id': 211672,
   'imdb_id': 'tt2293640',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Minions',
   'overview': 'Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.',
   'popularity': 10.9013,
   'poster_path': '/dr02BdCNAUPVU07aOodwPYv6HCf.jpg',
   'production_companies': [{'id': 6704,
     'logo_path': '/fOG2oY4m1YuYTQh4bMqqZkmgOAI.png',
     'name': 'Illumination',
     'origin_country': 'US'},
    {'id': 33,
     'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
     'name': 'Universal Pictures',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-06-17',
   'revenue': 1159457503,
   'runtime': 91,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'Go back to where it all began.',
   'title': 'Minions',
   'video': False,
   'vote_average': 6.421,
   'vote_count': 11184},
  {'adult': False,
   'backdrop_path': '/8lBViysvNJBPkl6zG1LVAaW3qhj.jpg',
   'belongs_to_collection': {'id': 645,
    'name': 'James Bond Collection',
    'poster_path': '/ofwSiqOFShhunAIYYdSMHMJQSx2.jpg',
    'backdrop_path': '/dOSECZImeyZldoq0ObieBE0lwie.jpg'},
   'budget': 245000000,
   'genres': [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 53, 'name': 'Thriller'}],
   'homepage': 'https://mgm.com/movies/spectre',
   'id': 206647,
   'imdb_id': 'tt2379713',
   'origin_country': ['GB'],
   'original_language': 'en',
   'original_title': 'Spectre',
   'overview': 'A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.',
   'popularity': 10.7827,
   'poster_path': '/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg',
   'production_companies': [{'id': 21,
     'logo_path': '/usUnaYV6hQnlVAXP6r4HwrlLFPG.png',
     'name': 'Metro-Goldwyn-Mayer',
     'origin_country': 'US'},
    {'id': 5,
     'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
     'name': 'Columbia Pictures',
     'origin_country': 'US'},
    {'id': 7576,
     'logo_path': '/oYcUi1byZ312Z3xiz5ojz9RQLND.png',
     'name': 'EON Productions',
     'origin_country': 'GB'}],
   'production_countries': [{'iso_3166_1': 'GB', 'name': 'United Kingdom'},
    {'iso_3166_1': 'US', 'name': 'United States of America'}],
   'release_date': '2015-10-26',
   'revenue': 880707597,
   'runtime': 148,
   'softcore': False,
   'spoken_languages': [{'english_name': 'French',
     'iso_639_1': 'fr',
     'name': 'Français'},
    {'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'},
    {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'},
    {'english_name': 'Italian', 'iso_639_1': 'it', 'name': 'Italiano'},
    {'english_name': 'German', 'iso_639_1': 'de', 'name': 'Deutsch'}],
   'status': 'Released',
   'tagline': 'The Dead Are Alive.',
   'title': 'Spectre',
   'video': False,
   'vote_average': 6.571,
   'vote_count': 11343},
  {'adult': False,
   'backdrop_path': '/o3i6AfTcWAuNvzAUV3q5lOmi6Gx.jpg',
   'belongs_to_collection': {'id': 1022790,
    'name': 'Inside Out Collection',
    'poster_path': '/kvJqs0vm29U0xJa373wlzHb3FRh.jpg',
    'backdrop_path': '/7hYG0v6BEErqqwnU7vWJjWgYJJp.jpg'},
   'budget': 175000000,
   'genres': [{'id': 16, 'name': 'Animation'},
    {'id': 10751, 'name': 'Family'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 18, 'name': 'Drama'},
    {'id': 35, 'name': 'Comedy'}],
   'homepage': 'http://movies.disney.com/inside-out',
   'id': 150540,
   'imdb_id': 'tt2096673',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Inside Out',
   'overview': 'When 11-year-old Riley moves to a new city, her Emotions team up to help her through the transition. Joy, Fear, Anger, Disgust and Sadness work together, but when Joy and Sadness get lost, they must journey through unfamiliar places to get back home.',
   'popularity': 26.6941,
   'poster_path': '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
   'production_companies': [{'id': 3,
     'logo_path': '/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png',
     'name': 'Pixar',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-06-17',
   'revenue': 857611174,
   'runtime': 95,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'Meet the little voices inside your head.',
   'title': 'Inside Out',
   'video': False,
   'vote_average': 7.908,
   'vote_count': 23652},
  {'adult': False,
   'backdrop_path': '/vYIUN5rrCncHFY8WvcuXQlM4hk5.jpg',
   'belongs_to_collection': {'id': 87359,
    'name': 'Mission: Impossible Collection',
    'poster_path': '/geEjCGfdmRAA1skBPwojcdvnZ8A.jpg',
    'backdrop_path': '/mroWh717g0Ah2c0rrPGW6f3EWMM.jpg'},
   'budget': 150000000,
   'genres': [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}],
   'homepage': '',
   'id': 177677,
   'imdb_id': 'tt2381249',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Mission: Impossible - Rogue Nation',
   'overview': "Ethan and team take on their most impossible mission yet—eradicating 'The Syndicate', an International and highly-skilled rogue organization committed to destroying the IMF.",
   'popularity': 11.2969,
   'poster_path': '/fRJLXQBHK2wyznK5yZbO7vmsuVK.jpg',
   'production_companies': [{'id': 4,
     'logo_path': '/jay6WcMgagAklUt7i9Euwj1pzTF.png',
     'name': 'Paramount Pictures',
     'origin_country': 'US'},
    {'id': 11461,
     'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
     'name': 'Bad Robot',
     'origin_country': 'US'},
    {'id': 69485, 'logo_path': None, 'name': 'Odin', 'origin_country': ''},
    {'id': 82819,
     'logo_path': '/gXfFl9pRPaoaq14jybEn1pHeldr.png',
     'name': 'Skydance Media',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-07-28',
   'revenue': 682716636,
   'runtime': 131,
   'softcore': False,
   'spoken_languages': [{'english_name': 'German',
     'iso_639_1': 'de',
     'name': 'Deutsch'},
    {'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'},
    {'english_name': 'Swedish', 'iso_639_1': 'sv', 'name': 'svenska'}],
   'status': 'Released',
   'tagline': 'Desperate times. Desperate measures.',
   'title': 'Mission: Impossible - Rogue Nation',
   'video': False,
   'vote_average': 7.225,
   'vote_count': 9807},
  {'adult': False,
   'backdrop_path': '/qVgLMRVNB5bHU0inmRa0ueShacN.jpg',
   'belongs_to_collection': {'id': 131635,
    'name': 'The Hunger Games Collection',
    'poster_path': '/cEBNDEMGqvSvU0knEv9Wl3dk5kv.jpg',
    'backdrop_path': '/Ipp7cegtub4t0mu7xaKLQkYoGc.jpg'},
   'budget': 160000000,
   'genres': [{'id': 28, 'name': 'Action'},
    {'id': 12, 'name': 'Adventure'},
    {'id': 878, 'name': 'Science Fiction'}],
   'homepage': 'http://www.thehungergames.movie/',
   'id': 131634,
   'imdb_id': 'tt1951266',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'The Hunger Games: Mockingjay - Part 2',
   'overview': 'As the war between the Capitol and the districts reaches its peak, Katniss Everdeen embarks on a perilous mission to liberate Panem and confront President Snow. Joined by a team of trusted allies, she navigates deadly traps, shifting loyalties, and the heavy cost of rebellion, determined to bring freedom to her people and end the Hunger Games once and for all.',
   'popularity': 9.8635,
   'poster_path': '/lImKHDfExAulp16grYm8zD5eONE.jpg',
   'production_companies': [{'id': 1632,
     'logo_path': '/cisLn1YAUuptXVBa0xjq7ST9cH0.png',
     'name': 'Lionsgate',
     'origin_country': 'US'},
    {'id': 5420,
     'logo_path': '/dlW4Kh5dNieKNURnymsu57y6fMf.png',
     'name': 'Color Force',
     'origin_country': 'US'},
    {'id': 264,
     'logo_path': '/fA90qwUKgPhMONqtwY60GaHRyrW.png',
     'name': 'Studio Babelsberg',
     'origin_country': 'DE'}],
   'production_countries': [{'iso_3166_1': 'DE', 'name': 'Germany'},
    {'iso_3166_1': 'US', 'name': 'United States of America'}],
   'release_date': '2015-11-18',
   'revenue': 653428261,
   'runtime': 137,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'}],
   'status': 'Released',
   'tagline': 'The fire will burn forever.',
   'title': 'The Hunger Games: Mockingjay - Part 2',
   'video': False,
   'vote_average': 6.902,
   'vote_count': 13449},
  {'adult': False,
   'backdrop_path': '/lzMS0CI3FLQYC5EgJoWeIaEt0lm.jpg',
   'belongs_to_collection': None,
   'budget': 108000000,
   'genres': [{'id': 878, 'name': 'Science Fiction'},
    {'id': 18, 'name': 'Drama'},
    {'id': 12, 'name': 'Adventure'}],
   'homepage': 'https://www.20thcenturystudios.com/movies/the-martian',
   'id': 286217,
   'imdb_id': 'tt3659388',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'The Martian',
   'overview': 'During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.',
   'popularity': 22.949,
   'poster_path': '/pjYWdykADVLTCh5g475RnI2hWIN.jpg',
   'production_companies': [{'id': 28788,
     'logo_path': '/Aqomtf9oh5dKtxBNEagkdlp3aGv.png',
     'name': 'Genre Films',
     'origin_country': 'US'},
    {'id': 22213,
     'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
     'name': 'TSG Entertainment',
     'origin_country': 'US'},
    {'id': 25,
     'logo_path': '/nM2MfoMqzJQRiSynsDabOtFKetD.png',
     'name': '20th Century Fox',
     'origin_country': 'US'},
    {'id': 221347,
     'logo_path': '/6Ry6uNBaa0IbbSs1XYIgX5DkA9r.png',
     'name': 'Scott Free Productions',
     'origin_country': 'US'}],
   'production_countries': [{'iso_3166_1': 'US',
     'name': 'United States of America'}],
   'release_date': '2015-09-30',
   'revenue': 631058917,
   'runtime': 141,
   'softcore': False,
   'spoken_languages': [{'english_name': 'English',
     'iso_639_1': 'en',
     'name': 'English'},
    {'english_name': 'Mandarin', 'iso_639_1': 'zh', 'name': '普通话'}],
   'status': 'Released',
   'tagline': 'Bring him home.',
   'title': 'The Martian',
   'video': False,
   'vote_average': 7.706,
   'vote_count': 21509},
  {'adult': False,
   'backdrop_path': '/7IGKrY1f1KfwMipx9wZC4NRgIdF.jpg',
   'belongs_to_collection': {'id': 344830,
    'name': 'Fifty Shades Collection',
    'poster_path': '/29sMhnMJPHsbO2XHu35iQjk4eFR.jpg',
    'backdrop_path': '/f7F56YyMX9G6L4ffqNpA9zlG6fm.jpg'},
   'budget': 40000000,
   'genres': [{'id': 18, 'name': 'Drama'},
    {'id': 10749, 'name': 'Romance'},
    {'id': 53, 'name': 'Thriller'}],
   'homepage': 'https://www.facebook.com/fiftyshadesofgreymovie',
   'id': 216015,
   'imdb_id': 'tt2322441',
   'origin_country': ['US'],
   'original_language': 'en',
   'original_title': 'Fifty Shades of Grey',
   'overview': "When college senior Anastasia Steele steps in for her sick roommate to interview prominent businessman Christian Grey for their campus paper, little does she realize the path her life will take. Christian, as enigmatic as he is rich and powerful, finds himself strangely drawn to Ana, and she to him. Though sexually inexperienced, Ana plunges headlong into an affair -- and learns that Christian's true sexual proclivities push the boundaries of pain and pleasure.",
   'popularity': 20.7145,
   'poster_path': '/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg',
   'production_companies': [{'id': 33,
     'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
     'name': 'Universal Pictures',
     'origin_country': 'US'},
    {'id': 10146,
     'logo_path': '/xnFIOeq5cKw09kCWqV7foWDe4AA.png',
     'name': 'Focus Features',
     'origin_country': 'US'},
    {'id': 11370,
     'logo_path': None,

## Transforming the data

After loading the json files, I use json normalize, and set record_path equal to movies so that each movie represents a single row. I also add a year column to the dataframe.

In [87]:
df_movie_details = pd.json_normalize(raw_details, record_path="movies")

In [88]:
df_movie_details.head(5)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,tagline,title,video,vote_average,vote_count,belongs_to_collection.id,belongs_to_collection.name,belongs_to_collection.poster_path,belongs_to_collection.backdrop_path,belongs_to_collection
0,False,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,[US],en,Star Wars: The Force Awakens,...,Every generation has a story.,Star Wars: The Force Awakens,False,7.248,20688,10.0,Star Wars Collection,/pWVLFh4OuejTpUaDQbB1C4zoS2p.jpg,/iY2ujEY2m68OTTlPFTiHub9joHS.jpg,NaN
1,False,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.jurassicworld.com/,135397,tt0369610,[US],en,Jurassic World,...,The park is open.,Jurassic World,False,6.703,21726,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/njFixYzIxX8jsn6KMSEtAzi4avi.jpg,NaN
2,False,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.universalpicturesathome.com/movies...,168259,tt2820852,[US],en,Furious 7,...,Vengeance hits home.,Furious 7,False,7.216,11381,9485.0,The Fast and the Furious Collection,/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg,/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg,NaN
3,False,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/avengers-age-of-...,99861,tt2395427,[US],en,Avengers: Age of Ultron,...,A new age has come.,Avengers: Age of Ultron,False,7.275,24664,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/2UNUv4NJdC36E5myDHACBJ99EwL.jpg,NaN
4,False,/wKrxeY6lbu7KFBsWVcMH6M8avwr.jpg,74000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",http://www.minionsmovie.com/,211672,tt2293640,[US],en,Minions,...,Go back to where it all began.,Minions,False,6.421,11184,544669.0,Minions Collection,/lqU48HkuPDpbumwHk9syT7FbxpC.jpg,/62Qe28oi9PaK3P2ljDYUDTGAyST.jpg,NaN

I only pick the relevant columns for my analysis and the **export** it to a csv file

In [89]:
cols_to_keep = ['id', 'title', 'original_title', 'release_date',
                 'budget', 'revenue', 'popularity', 'vote_average', 
                 'vote_count', 'runtime', 'original_language']

df_movie_details = df_movie_details[cols_to_keep]

In [90]:
df_movie_details["year"] = pd.to_datetime(df_movie_details["release_date"]).dt.year

I figured that TMDB probably uses `runtime = 0` as a placeholder when it has no runtime data for a film, rather than the film genuinely being zero minutes long. Since runtime is central to this analysis, I drop those rows here so I don't have to keep filtering them out downstream. Note this only catches exact zeros — a handful of films still have implausibly short but nonzero runtimes (as low as 1 minute), which slip past this filter and are instead flagged later, in NB03.

In [91]:
df_movie_details = df_movie_details[df_movie_details["runtime"] != 0]

In [92]:
df_movie_details.to_csv('../data/processed/movies.csv')

In [93]:
df_movie_details

,id,title,original_title,release_date,budget,revenue,popularity,vote_average,vote_count,runtime,original_language,year
0,140607,Star Wars: The Force Awakens,Star Wars: The Force Awakens,2015-12-15,245000000,2068223624,21.4627,7.248,20688,136,en,2015
1,135397,Jurassic World,Jurassic World,2015-06-06,150000000,1671537444,18.7528,6.703,21726,124,en,2015
2,168259,Furious 7,Furious 7,2015-04-01,190000000,1515400000,13.9605,7.216,11381,138,en,2015
3,99861,Avengers: Age of Ultron,Avengers: Age of Ultron,2015-04-22,235000000,1405403694,33.7251,7.275,24664,141,en,2015
4,211672,Minions,Minions,2015-06-17,74000000,1159457503,10.9013,6.421,11184,91,en,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
1095,1230368,Springsteen: Deliver Me from Nowhere,Springsteen: Deliver Me from Nowhere,2025-10-22,55000000,45240624,4.2320,6.631,321,120,en,2025
1096,1539104,JUJUTSU KAISEN: Execution,劇場版 呪術廻戦「渋谷事変 特別編集版」×「死滅回游 先行上映」,2025-11-07,0,44457030,18.0459,6.041,109,88,ja,2025
1097,1408208,Exit 8,８番出口,2025-08-29,1400000,43892680,13.3526,7.004,643,95,ja,2025
1098,1233575,Black Bag,Black Bag,2025-03-12,50000000,43887905,6.7802,6.367,1294,94,en,2025
1099,701387,Bugonia,Bugonia,2025-10-23,55000000,43500000,19.2877,7.304,2161,119,en,2025

Since I'll be grouping data according to movie genres after, I make a dataframe in which each row represents one single genre. I drop the duplicates after, so as to not have repeated genres. I then export it into a csv.

In [94]:
df_genres = pd.json_normalize(
    raw_details['movies'],
    record_path=['genres'],
    record_prefix='genre_' 
)

df_genres

      genre_id       genre_name
0           12        Adventure
1           28           Action
2          878  Science Fiction
3           12        Adventure
4          878  Science Fiction
...        ...              ...
3187      9648          Mystery
3188        53         Thriller
3189       878  Science Fiction
3190        53         Thriller
3191        35           Comedy

[3192 rows x 2 columns]

In [95]:
df_genres = df_genres.drop_duplicates()

In [96]:
df_genres.to_csv("../data/processed/genres.csv")

Furthermore, I also create a dataframe that connects both the movies and the genres. This dataframe will hold information about the genre_id, as well as the movie id. After, I export it into a csv file.

I filter this table down to only the movie IDs that survived the `runtime != 0` cleanup above. Without this, `df_genres_movie` — built directly from the raw JSON — would still include genre links for movies I've already dropped, which would violate the foreign key from `movie_genres` to `movies` once the schema below enforces it.

In [97]:
df_genres_movie = pd.json_normalize(
    raw_details['movies'],
    record_path=['genres'],
    meta=['id'],
    record_prefix='genre_' 
)

df_genres_movie = df_genres_movie[df_genres_movie["id"].isin(df_movie_details["id"])]

In [98]:
df_genres_movie.to_csv("../data/processed/genres_movie.csv")

## Making a database

First, I make a connection to the database and enforce database integrity

In [99]:
conn = sqlite3.connect("../data/movies.db")

In [100]:
conn.execute("PRAGMA foreign_keys = ON;")

This block of code is written in SQL, and it creates the tables.

I split the data into **three tables** instead of one wide table: `movies` holds one row per film; `genres` holds each unique genre once, keyed by `genre_id`; and `movie_genres` is a join table linking movie IDs to genre IDs. A join table is necessary because the relationship is many-to-many — one film can have several genres, and one genre covers many films — which a single flat table can't represent without duplicating movie rows once per genre. The `FOREIGN KEY` on `movie_genres.id` ties every genre link back to a real row in `movies`, which is what `PRAGMA foreign_keys = ON` above actually enforces.

In [101]:
schema_query_movies = """
DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255),
    original_title VARCHAR(255),
    release_date DATE,
    budget BIGINT,
    revenue BIGINT,
    popularity DECIMAL(10,4),
    vote_average DECIMAL(4,3),
    vote_count INTEGER,
    runtime INTEGER,
    original_language VARCHAR(10),
    year INT
);
"""
schema_query_genres = """

DROP TABLE IF EXISTS genres;

CREATE TABLE genres (
    genre_id INTEGER PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL
)


"""

schema_query_genres_movies = """
DROP TABLE IF EXISTS movie_genres;


CREATE TABLE movie_genres (
    id BIGINT,
    genre_id INTEGER,
    genre_name VARCHAR(50),
    PRIMARY KEY (id, genre_id),
    FOREIGN KEY (id) REFERENCES movies(id)
);
"""

conn.executescript(schema_query_genres)
conn.executescript(schema_query_genres_movies)
conn.executescript(schema_query_movies)

After that, pandas is able to read the csv files and populates each table with the correct dataframe.

In [102]:
df_movie_details.to_sql(
    "movies",
    conn,
    if_exists="append", 
    index=False
)

df_genres.to_sql(
    "genres",
    conn,
    if_exists="append", 
    index=False

)


df_genres_movie.to_sql(
    "movie_genres",
    conn,
    if_exists="append", 
    index=False
)

3175

This query shows the tables created in the database

In [103]:
tables_df = pd.read_sql("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
""", conn)

print(tables_df)

           name
0        genres
1  movie_genres
2        movies

## Summary

This notebook turned the raw TMDB JSON into three normalized tables — `movies`, `genres`, and `movie_genres` — written both to CSVs in `data/processed/` and to a SQLite database at `data/movies.db`. NB03 reads from this database to build the analysis.