In [1]:
import pandas as pd 
import json

In [2]:
with open("../data/raw/movie_details.json") as f:
    raw_details = json.load(f)

In [3]:
df_movie_details = pd.json_normalize(raw_details, record_path="movies")

In [8]:
df_movie_details.head(5)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,...,tagline,title,video,vote_average,vote_count,belongs_to_collection.id,belongs_to_collection.name,belongs_to_collection.poster_path,belongs_to_collection.backdrop_path,belongs_to_collection
0,False,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,[US],en,Star Wars: The Force Awakens,...,Every generation has a story.,Star Wars: The Force Awakens,False,7.247,20683,10.0,Star Wars Collection,/pWVLFh4OuejTpUaDQbB1C4zoS2p.jpg,/iY2ujEY2m68OTTlPFTiHub9joHS.jpg,NaN
1,False,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.jurassicworld.com/,135397,tt0369610,[US],en,Jurassic World,...,The park is open.,Jurassic World,False,6.703,21725,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/njFixYzIxX8jsn6KMSEtAzi4avi.jpg,NaN
2,False,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.universalpicturesathome.com/movies...,168259,tt2820852,[US],en,Furious 7,...,Vengeance hits home.,Furious 7,False,7.216,11380,9485.0,The Fast and the Furious Collection,/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg,/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg,NaN
3,False,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/avengers-age-of-...,99861,tt2395427,[US],en,Avengers: Age of Ultron,...,A new age has come.,Avengers: Age of Ultron,False,7.276,24658,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/2UNUv4NJdC36E5myDHACBJ99EwL.jpg,NaN
4,False,/wKrxeY6lbu7KFBsWVcMH6M8avwr.jpg,74000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",http://www.minionsmovie.com/,211672,tt2293640,[US],en,Minions,...,Go back to where it all began.,Minions,False,6.400,11183,544669.0,Minions Collection,/lqU48HkuPDpbumwHk9syT7FbxpC.jpg,/62Qe28oi9PaK3P2ljDYUDTGAyST.jpg,NaN

In [13]:
cols_to_keep = ['id', 'title', 'original_title', 'release_date',
                 'budget', 'revenue', 'popularity', 'vote_average', 
                 'vote_count', 'runtime', 'original_language']

df_movie_details = df_movie_details[cols_to_keep]

In [14]:
df_movie_details

,id,title,original_title,release_date,budget,revenue,popularity,vote_average,vote_count,runtime,original_language
0,140607,Star Wars: The Force Awakens,Star Wars: The Force Awakens,2015-12-15,245000000,2068223624,20.3809,7.247,20683,136,en
1,135397,Jurassic World,Jurassic World,2015-06-06,150000000,1671537444,17.6481,6.703,21725,124,en
2,168259,Furious 7,Furious 7,2015-04-01,190000000,1515400000,13.5557,7.216,11380,138,en
3,99861,Avengers: Age of Ultron,Avengers: Age of Ultron,2015-04-22,235000000,1405403694,32.2323,7.276,24658,141,en
4,211672,Minions,Minions,2015-06-17,74000000,1159457503,11.0753,6.400,11183,91,en
...,...,...,...,...,...,...,...,...,...,...,...
215,1432484,The World of the Pharaoh (Live Theatre),The World of the Pharaoh (Live Theatre),2025-02-09,1000000,500000000,0.1086,10.000,1,0,es
216,1038392,The Conjuring: Last Rites,The Conjuring: Last Rites,2025-09-03,55000000,499256445,23.1276,6.953,2005,136,en
217,1500536,Dead to Rights,南京照相馆,2025-07-19,20000000,422785908,2.9549,8.000,84,137,zh
218,822119,Captain America: Brave New World,Captain America: Brave New World,2025-02-12,180000000,415101577,37.2312,5.965,3202,119,en
219,1368166,The Housemaid,The Housemaid,2025-12-18,35000000,399644671,49.9536,7.277,2719,131,en

In [36]:
df_movie_details.to_csv('../data/processed/movies.csv')

In [23]:
df_genres = pd.json_normalize(
    raw_details['movies'],
    record_path=['genres'],
    record_prefix='genre_' 
)

In [33]:
df_genres = df_genres.drop_duplicates()

In [35]:
df_genres.to_csv("../data/processed/genres.csv")

In [24]:
df_genres_movie = pd.json_normalize(
    raw_details['movies'],
    record_path=['genres'],
    meta=['id'],
    record_prefix='genre_' 
)

In [25]:
df_genres_movie.to_csv("../data/processed/genres_movie.csv")

In [37]:
genres

     genre_id       genre_name
0          12        Adventure
1          28           Action
2         878  Science Fiction
3          12        Adventure
4         878  Science Fiction
..        ...              ...
687        28           Action
688        53         Thriller
689       878  Science Fiction
690      9648          Mystery
691        53         Thriller

[692 rows x 2 columns]